export const GET_COUNTRIES_API = "GET/COUNTRIES/API";
export const GET_COUNTRIES_SEARCH = "GET/COUNTRIES/SEARCH";

export const GET_ACTIVITIES_API = "GET/ACTIVITIES/API";

export const SORT_COUNTRIES_POPULATION = 'SORT/COUNTRIES/POPULATION';
export const SORT_COUNTRIES_ALPHABET = 'SORT/COUNTRIES/ALPHABET';

export const FILTER_COUNTRIES_CONTINENT = "FILTER/COUNTRIES/CONTINENT";
export const FILTER_COUNTRIES_ACTIVITIES = "FILTER/COUNTRIES/ACTIVITIES";

export const SET_COUNTRIES_PAGINATION = "SET/COUNTRIES/PAGINATION"

export const SET_LOADING = 'SET/LOADING';